"""更新user_profiles表：新增字段，约束输入

Revision ID: 0fee0d96d50d
Revises: f21fdda53347
Create Date: 2026-06-26 13:48:12.796392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fee0d96d50d'
down_revision: Union[str, Sequence[str], None] = 'f21fdda53347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_learning_level', sa.Enum('beginner', 'entry', 'advanced'), nullable=True, comment='学习水平：beginner=初学，entry=入门，advanced=进阶'))
    op.add_column('user_profiles', sa.Column('profile_support_style', sa.Enum('gentle', 'direct', 'coach', 'warm_logic'), nullable=True, comment='情绪陪伴风格'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profile_support_style')
    op.drop_column('user_profiles', 'profile_learning_level')
    # ### end Alembic commands ###
