"""初始化数据表

Revision ID: 1d20baff3943
Revises: 
Create Date: 2026-06-24 15:38:53.786751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d20baff3943'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='user_gender'), nullable=True, comment='性别'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='个人简介'),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), nullable=False, comment='账号状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('daily_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='每日复盘ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('review_date', sa.DateTime(), nullable=False, comment='复盘日期'),
    sa.Column('mainline_progress', sa.TEXT(), nullable=True, comment='主线推进情况'),
    sa.Column('learned_summary', sa.TEXT(), nullable=True, comment='今日学习总结'),
    sa.Column('problems', sa.TEXT(), nullable=True, comment='今日问题'),
    sa.Column('branch_summary', sa.TEXT(), nullable=True, comment='今日分支情况'),
    sa.Column('emotion_summary', sa.TEXT(), nullable=True, comment='今日情绪状态'),
    sa.Column('tomorrow_plan', sa.TEXT(), nullable=True, comment='明日计划'),
    sa.Column('ai_feedback', sa.TEXT(), nullable=True, comment='AI反馈'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reviews')),
    sa.UniqueConstraint('user_id', 'review_date', name='uq_daily_reviews_user_date')
    )
    op.create_index('ix_daily_reviews_user_date', 'daily_reviews', ['user_id', 'review_date'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='知识点ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='知识点名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='知识点描述'),
    sa.Column('domain', sa.String(length=50), nullable=True, comment='知识点所属领域'),
    sa.Column('mastery_level', sa.Integer(), nullable=True, comment='知识点掌握程度(1-5)'),
    sa.Column('importance_level', sa.Integer(), nullable=True, comment='知识点重要程度(1-5)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_points_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_points')),
    sa.UniqueConstraint('user_id', 'name', 'domain', name='uq_knowledge_points_user_name_domain')
    )
    op.create_index('ix_knowledge_points_user_domain', 'knowledge_points', ['user_id', 'domain'], unique=False)
    op.create_table('learning_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学习目标ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='学习目标标题'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='学习目标描述'),
    sa.Column('direction', sa.String(length=255), nullable=False, comment='学习目标方向'),
    sa.Column('status', sa.Enum('pending', 'active', 'paused', 'completed', 'archived', name='learning_goal_status'), nullable=False, comment='学习目标状态'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='学习目标优先级'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='学习目标开始时间'),
    sa.Column('target_date', sa.DateTime(), nullable=True, comment='学习目标完成时间'),
    sa.Column('current_stage', sa.String(length=255), nullable=True, comment='学习目标当前阶段'),
    sa.Column('current_principle', sa.String(length=255), nullable=True, comment='当前学习原则'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goals'))
    )
    op.create_index('ix_learning_goals_user_priority', 'learning_goals', ['user_id', 'priority'], unique=False)
    op.create_index('ix_learning_goals_user_status', 'learning_goals', ['user_id', 'status'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='笔记ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='笔记标题'),
    sa.Column('raw_content', mysql.LONGTEXT(), nullable=False, comment='原始笔记内容'),
    sa.Column('optimized_content', mysql.LONGTEXT(), nullable=True, comment='AI优化后的结构化内容'),
    sa.Column('summary', sa.TEXT(), nullable=True, comment='AI笔记摘要'),
    sa.Column('note_type', sa.Enum('manual', 'ai_answer', 'branch_summary', 'file_import', name='note_type'), nullable=False, comment='笔记类型'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='来源类型'),
    sa.Column('source_id', sa.String(length=100), nullable=True, comment='来源ID'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='笔记标签'),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='note_status'), nullable=False, comment='笔记状态'),
    sa.Column('is_vectorized', sa.Boolean(), nullable=False, comment='笔记是否已向量化'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_source', 'notes', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_notes_user_created', 'notes', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notes_user_status', 'notes', ['user_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('public_id', sa.String(length=255), nullable=True, comment='会话公开ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('session_type', sa.Enum('chat', 'study', 'review', 'emotion', name='session_type'), nullable=False, comment='会话类型'),
    sa.Column('status', sa.Enum('active', 'archived', name='session_status'), nullable=False, comment='会话状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('public_id', name='uq_sessions_public_id')
    )
    op.create_index('ix_sessions_user_status', 'sessions', ['user_id', 'status'], unique=False)
    op.create_index('ix_sessions_user_type', 'sessions', ['user_id', 'session_type'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户画像ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('target_direction', sa.String(length=100), nullable=True, comment='学习目标方向'),
    sa.Column('anxiety_level', sa.Integer(), nullable=True, comment='焦虑等级(1-5)'),
    sa.Column('preference_json', sa.JSON(), nullable=True, comment='偏好JSON'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='每周复盘ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('week_start_date', sa.DateTime(), nullable=False, comment='周开始时间'),
    sa.Column('week_end_date', sa.DateTime(), nullable=False, comment='周结束时间'),
    sa.Column('mainline_summary', sa.TEXT(), nullable=True, comment='本周主线总结'),
    sa.Column('learned_summary', sa.TEXT(), nullable=True, comment='本周学习总结'),
    sa.Column('completed_goals', sa.TEXT(), nullable=True, comment='本周完成目标'),
    sa.Column('unfinished_goals', sa.TEXT(), nullable=True, comment='本周未完成目标'),
    sa.Column('repeated_problems', sa.TEXT(), nullable=True, comment='反复卡点'),
    sa.Column('emotion_pattern', sa.TEXT(), nullable=True, comment='情绪模式'),
    sa.Column('next_week_plan', sa.TEXT(), nullable=True, comment='下周计划'),
    sa.Column('ai_feedback', sa.TEXT(), nullable=True, comment='AI反馈'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reviews')),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_reviews_user_week_start')
    )
    op.create_index('ix_weekly_reviews_user_week', 'weekly_reviews', ['user_id', 'week_start_date'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='智能体运行记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话ID'),
    sa.Column('agent_name', sa.String(length=255), nullable=False, comment='智能体名称'),
    sa.Column('graph_name', sa.String(length=255), nullable=False, comment='图名称'),
    sa.Column('thread_id', sa.String(length=255), nullable=True, comment='LangGraph线程ID'),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=True, comment='Checkpointer检查点ID'),
    sa.Column('parent_run_id', sa.Integer(), nullable=True, comment='父运行ID'),
    sa.Column('intent', sa.String(length=255), nullable=True, comment='用户意图'),
    sa.Column('status', sa.Enum('running', 'interrupted', 'completed', 'failed', 'cancelled', name='agent_run_status'), nullable=False, comment='运行状态'),
    sa.Column('interrupt_reason', sa.String(length=255), nullable=True, comment='中断原因'),
    sa.Column('input_json', sa.JSON(), nullable=True, comment='输入参数'),
    sa.Column('output_json', sa.JSON(), nullable=True, comment='输出参数'),
    sa.Column('resume_payload', sa.JSON(), nullable=True, comment='恢复执行参数'),
    sa.Column('error_message', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_runs_parent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_agent_runs_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_session_created', 'agent_runs', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_thread_id', 'agent_runs', ['thread_id'], unique=False)
    op.create_index('ix_agent_runs_user_status', 'agent_runs', ['user_id', 'status'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='任务ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('goal_id', sa.Integer(), nullable=False, comment='所属学习目标ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='任务标题'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='任务描述'),
    sa.Column('task_type', sa.Enum('study', 'review', 'branch', 'reflection', name='daily_task_type'), nullable=False, comment='任务类型'),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='daily_task_status'), nullable=False, comment='任务状态'),
    sa.Column('estimated_time', sa.Integer(), nullable=True, comment='预计耗时(分钟)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], name=op.f('fk_daily_tasks_goal_id_learning_goals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tasks'))
    )
    op.create_index('ix_daily_tasks_goal_status', 'daily_tasks', ['goal_id', 'status'], unique=False)
    op.create_index('ix_daily_tasks_user_status', 'daily_tasks', ['user_id', 'status'], unique=False)
    op.create_table('emotion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='心情日志ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话ID'),
    sa.Column('emotion_type', sa.Enum('happy', 'anxious', 'sad', 'stressed', 'confused', 'angry', 'numb', name='emotion_type'), nullable=False, comment='心情类型'),
    sa.Column('intensity', sa.Integer(), nullable=False, comment='心情强度(1-5)'),
    sa.Column('trigger_text', sa.TEXT(), nullable=True, comment='触发原因'),
    sa.Column('ai_response_summary', sa.TEXT(), nullable=True, comment='AI回复摘要'),
    sa.Column('action_suggestion', sa.TEXT(), nullable=True, comment='行动建议'),
    sa.Column('support_mode', sa.String(length=50), nullable=True, comment='支持方式'),
    sa.Column('risk_level', sa.Enum('none', 'low', 'medium', 'high', name='emotion_risk_level'), nullable=False, comment='风险等级'),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False, comment='是否需要后续跟进'),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, comment='是否敏感'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_emotion_logs_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emotion_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotion_logs'))
    )
    op.create_index('ix_emotion_logs_session_created', 'emotion_logs', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_emotion_logs_user_created', 'emotion_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='message_role'), nullable=False, comment='消息角色'),
    sa.Column('content', mysql.LONGTEXT(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.Enum('text', 'markdown', 'tool_call', 'tool_result', name='message_type'), nullable=False, comment='消息类型'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='元数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_messages_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_messages_user_created', 'messages', ['user_id', 'created_at'], unique=False)
    op.create_table('note_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='笔记切片ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('note_id', sa.Integer(), nullable=False, comment='笔记ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切片索引'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='切片内容'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='切片内容哈希'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='切片token数量'),
    sa.Column('chroma_collection', sa.String(length=100), nullable=False, comment='Chroma集合名'),
    sa.Column('chroma_document_id', sa.String(length=255), nullable=False, comment='Chroma文档ID'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='向量元数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_chunks_note_id_notes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_note_chunks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_chunks')),
    sa.UniqueConstraint('note_id', 'chunk_index', name='uq_note_chunks_note_index')
    )
    op.create_index('ix_note_chunks_chroma_document', 'note_chunks', ['chroma_collection', 'chroma_document_id'], unique=False)
    op.create_index('ix_note_chunks_content_hash', 'note_chunks', ['content_hash'], unique=False)
    op.create_index('ix_note_chunks_user_note', 'note_chunks', ['user_id', 'note_id'], unique=False)
    op.create_table('note_knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='笔记知识点关系ID'),
    sa.Column('note_id', sa.Integer(), nullable=False, comment='笔记ID'),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False, comment='知识点ID'),
    sa.Column('relation_type', sa.String(length=50), nullable=False, comment='关系类型(例如提到、解释、前置依赖)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], name=op.f('fk_note_knowledge_points_knowledge_point_id_knowledge_points')),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_knowledge_points_note_id_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_knowledge_points')),
    sa.UniqueConstraint('note_id', 'knowledge_point_id', name='uq_note_knowledge_points_note_point')
    )
    op.create_index('ix_note_knowledge_points_note_id', 'note_knowledge_points', ['note_id'], unique=False)
    op.create_index('ix_note_knowledge_points_point_id', 'note_knowledge_points', ['knowledge_point_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='上传文件ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件路径'),
    sa.Column('file_type', sa.Enum('pdf', 'md', 'txt', 'docx', name='uploaded_file_type'), nullable=False, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件哈希'),
    sa.Column('status', sa.Enum('uploaded', 'parsed', 'failed', name='uploaded_file_status'), nullable=False, comment='处理状态'),
    sa.Column('created_note_id', sa.Integer(), nullable=True, comment='生成的笔记ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_note_id'], ['notes.id'], name=op.f('fk_uploaded_files_created_note_id_notes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploaded_files_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    op.create_index('ix_uploaded_files_created_note_id', 'uploaded_files', ['created_note_id'], unique=False)
    op.create_index('ix_uploaded_files_user_created', 'uploaded_files', ['user_id', 'created_at'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学习记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('goal_id', sa.Integer(), nullable=False, comment='所属学习目标ID'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='对应每日任务ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='学习记录标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='学习过程记录'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='学习时长(分钟)'),
    sa.Column('focus_score', sa.Integer(), nullable=True, comment='专注度得分'),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='learning_session_status'), nullable=False, comment='学习记录状态'),
    sa.Column('summary', sa.TEXT(), nullable=True, comment='学习总结'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], name=op.f('fk_learning_sessions_goal_id_learning_goals')),
    sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], name=op.f('fk_learning_sessions_task_id_daily_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index('ix_learning_sessions_goal_started', 'learning_sessions', ['goal_id', 'started_at'], unique=False)
    op.create_index('ix_learning_sessions_user_started', 'learning_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('branch_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分支ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('goal_id', sa.Integer(), nullable=False, comment='所属学习目标ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='来源学习记录ID'),
    sa.Column('source_note_id', sa.Integer(), nullable=True, comment='来源笔记ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='分支标题'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='分支描述'),
    sa.Column('reason', sa.TEXT(), nullable=True, comment='分支原因'),
    sa.Column('status', sa.Enum('pending', 'limited_learning', 'returned', 'converted_to_goal', 'archived', name='branch_topic_status'), nullable=False, comment='分支状态'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='分支优先级'),
    sa.Column('timebox_minutes', sa.Integer(), nullable=True, comment='建议限时学习分钟数'),
    sa.Column('minimum_understanding', sa.TEXT(), nullable=True, comment='最低可用理解'),
    sa.Column('return_summary', sa.TEXT(), nullable=True, comment='回归主线总结'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], name=op.f('fk_branch_topics_goal_id_learning_goals')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_branch_topics_session_id_learning_sessions')),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], name=op.f('fk_branch_topics_source_note_id_notes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_branch_topics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_topics'))
    )
    op.create_index('ix_branch_topics_goal_status', 'branch_topics', ['goal_id', 'status'], unique=False)
    op.create_index('ix_branch_topics_user_status', 'branch_topics', ['user_id', 'status'], unique=False)
    op.create_table('branch_timer_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分支限时学习记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('branch_topic_id', sa.Integer(), nullable=False, comment='分支主题ID'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='限时学习开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='限时学习结束时间'),
    sa.Column('planned_minutes', sa.Integer(), nullable=False, comment='计划学习分钟数'),
    sa.Column('actual_minutes', sa.Integer(), nullable=True, comment='实际学习分钟数'),
    sa.Column('result_summary', sa.String(length=500), nullable=True, comment='学习结果摘要'),
    sa.Column('return_to_mainline', sa.Boolean(), nullable=False, comment='是否返回主线'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['branch_topic_id'], ['branch_topics.id'], name=op.f('fk_branch_timer_sessions_branch_topic_id_branch_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_branch_timer_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_timer_sessions'))
    )
    op.create_index('ix_branch_timer_sessions_topic_started', 'branch_timer_sessions', ['branch_topic_id', 'started_at'], unique=False)
    op.create_index('ix_branch_timer_sessions_user_started', 'branch_timer_sessions', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_branch_timer_sessions_user_started', table_name='branch_timer_sessions')
    op.drop_index('ix_branch_timer_sessions_topic_started', table_name='branch_timer_sessions')
    op.drop_table('branch_timer_sessions')
    op.drop_index('ix_branch_topics_user_status', table_name='branch_topics')
    op.drop_index('ix_branch_topics_goal_status', table_name='branch_topics')
    op.drop_table('branch_topics')
    op.drop_index('ix_learning_sessions_user_started', table_name='learning_sessions')
    op.drop_index('ix_learning_sessions_goal_started', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('ix_uploaded_files_user_created', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_created_note_id', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_note_knowledge_points_point_id', table_name='note_knowledge_points')
    op.drop_index('ix_note_knowledge_points_note_id', table_name='note_knowledge_points')
    op.drop_table('note_knowledge_points')
    op.drop_index('ix_note_chunks_user_note', table_name='note_chunks')
    op.drop_index('ix_note_chunks_content_hash', table_name='note_chunks')
    op.drop_index('ix_note_chunks_chroma_document', table_name='note_chunks')
    op.drop_table('note_chunks')
    op.drop_index('ix_messages_user_created', table_name='messages')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_emotion_logs_user_created', table_name='emotion_logs')
    op.drop_index('ix_emotion_logs_session_created', table_name='emotion_logs')
    op.drop_table('emotion_logs')
    op.drop_index('ix_daily_tasks_user_status', table_name='daily_tasks')
    op.drop_index('ix_daily_tasks_goal_status', table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_index('ix_agent_runs_user_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_thread_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_session_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_weekly_reviews_user_week', table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_sessions_user_type', table_name='sessions')
    op.drop_index('ix_sessions_user_status', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_notes_user_status', table_name='notes')
    op.drop_index('ix_notes_user_created', table_name='notes')
    op.drop_index('ix_notes_source', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_learning_goals_user_status', table_name='learning_goals')
    op.drop_index('ix_learning_goals_user_priority', table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_index('ix_knowledge_points_user_domain', table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index('ix_daily_reviews_user_date', table_name='daily_reviews')
    op.drop_table('daily_reviews')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
