"""更新daily_tasks表，新增task_date字段

Revision ID: bf6b342f5890
Revises: 0fee0d96d50d
Create Date: 2026-07-01 16:24:23.457624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6b342f5890'
down_revision: Union[str, Sequence[str], None] = '0fee0d96d50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('task_date', sa.Date(), nullable=False, comment='计划执行日期'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_tasks', 'task_date')
    # ### end Alembic commands ###
