"""更新users表：更改avatar_url大小

Revision ID: f21fdda53347
Revises: 1d20baff3943
Create Date: 2026-06-25 18:38:44.657296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f21fdda53347'
down_revision: Union[str, Sequence[str], None] = '1d20baff3943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_comment='头像URL',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_comment='头像URL',
               existing_nullable=True)
    # ### end Alembic commands ###
